### ISSUE TITLE
deepWatch doesn't accept an array of strings as expression to watch

### ISSUE THREAD

**Issue by matikun86** [decipherinc/angular-history#44]
I tried passing an Array of expressions to ```deepWatch``` like this:
```Javascript
History.deepWatch([
  'child.innerHTML for child in children',
  'child.attributes for child in children'
  ], $scope)
```
but got an exception as it is trying to use ```exp.match```. [But doc says it accepts an array of strings](http://decipherinc.github.io/angular-history/docs/#/api/decipher.history.service:History#deepWatch)

>Parameters
exp – {(string|string[])} – Expression or array of expressions to watch

**Comment by boneskull** [comment]
@matikun86 good catch.  yes, the jsdoc is incorrect.  if you would like this functionality, please send a PR!

I'll fix the jsdoc for now
